# Site settings
title: 아무거나 (github)
default_author: bkjeon
description: "Bkjeon Github Page"  # used in site head

# register on google analytics and replace this token
google_analytics: UA-123731292-1
# disque comments are broken if you send http:// along with url, this url is same as the one given on disqus
# Deleting the value would remove it from footer.
disqus_url: https://bkjeon1614.github.io/
disqus_id: bkjeon1614
# register on feedburner and replace this url. Deleting the value will remove it from footer.
feedburner_url: gcijdfdo@gmail.com

# footer details. Deleting the value would remove it from footer.
github_username:  bkjeon1614
facebook_username:
email: gcijdfdo@gmail.com
stackoverflow_username:
keybase_username :
copyright_name: BongKeun - Jeon
rss : false

# used for portfolio on home page
collections:
  - portfolio

# used to estimate reading time
wpm: 150

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
port: 8888
permalink: /blog/:title

# jekyll-paginate. for paginating blog posts.
paginate: 5
paginate_path: blog/page:num

# gem dependencies
plugins: [jekyll-paginate, jekyll-feed, jekyll-gist]
